export enum BagStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  SUBMITTED = 'SUBMITTED',
  ACCEPTED = 'ACCEPTED',
  COMPLETED = 'COMPLETED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  REFUNDED = 'REFUNDED',
  REJECTED = 'REJECTED',
  CANCELED = 'CANCELED',
  BACKORDERED = 'BACKORDERED',
}
