export enum FulfillmentStatus {
  PROCESSING = 'PROCESSING',
  SHIPPED = 'SHIPPED',
  PARTIALLY_SHIPPED = 'PARTIALLY_SHIPPED',
  DELIVERED = 'DELIVERED',
  COULD_NOT_DELIVER = 'COULD_NOT_DELIVER',
  RETURNED = 'RETURNED',
}
